// svelte-example/src/App.svelte
<script lang="ts">
  import { DashboardThemes, darkTheme } from "@frc-web-components/fwc/themes"
  import Examples from "./lib/Examples.svelte"
  const themes = new DashboardThemes()
  themes.addThemeRules("dark", darkTheme)

  let theme = "light"


  function updateTheme(newTheme: string) {
    theme = newTheme
    themes.setTheme(document.body, theme)
  }

</script>

<div class="App">
  <div class="theme-chooser">
    <label>
      <input
        type="radio"
        name="theme-chooser"
        on:click={() => {
          updateTheme('light')
        }}
        checked={theme === "light"}
      />{" "}
      Light Theme
    </label>
    <label>
      <input
        type="radio"
        name="theme-chooser"
        on:click={() => {
          updateTheme('dark')
        }}
        checked={theme === "dark"}
      />{" "}
      Dark Theme
    </label>
  </div>
  <Examples />
</div>

// react-example/src/App.tsx
import React, { useEffect, useRef, useState } from "react";
import Examples from "./examples/Examples";
import "./App.css";
import { DashboardThemes, darkTheme } from "@frc-web-components/fwc/themes";

const themes = new DashboardThemes();
themes.addThemeRules("dark", darkTheme);

function App() {
  const dashboardThemes = useRef<DashboardThemes>(themes);
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    dashboardThemes.current.setTheme(document.body, theme);
  }, [theme]);

  return (
    <div className="App">
      <div className="theme-chooser">
        <label>
          <input
            type="radio"
            name="theme-chooser"
            onClick={() => setTheme("light")}
            checked={theme === "light"}
          />{" "}
          Light Theme
        </label>
        <label>
          <input
            type="radio"
            name="theme-chooser"
            onClick={() => setTheme("dark")}
            checked={theme === "dark"}
          />{" "}
          Dark Theme
        </label>
      </div>
      <Examples />
    </div>
  );
}

export default App;
